"""
pretrain_bc.py — Behavioral cloning pretraining for DQN and PPO networks.

Loads the expert dataset generated by generate_bc_data.py and trains the
specified model to predict HeuristicBot's actions via cross-entropy loss.
The resulting checkpoint is passed to the RL training script via --checkpoint
to warm-start the learning phase.

Why cross-entropy and not MSE on Q-values / value targets?
    Behavioral cloning is a supervised classification problem: given a state,
    predict which action the expert took. Cross-entropy with the expert action
    as the label directly maximises the probability assigned to the expert's
    choice. MSE on Q-values would require defining target Q-values, which
    we don't have — we only have the expert's action.

DQN model (--model dqn):
    F.cross_entropy(logits, actions) — logits are raw Q-values after masking
    illegal actions to -1e9. Standard cross-entropy applies log_softmax internally.

PPO models (--model baseline/resnet/bfs/bfs_resnet):
    model.forward() returns (Categorical distribution, value scalar).
    The Categorical's .logits attribute already holds log_softmax(masked_logits),
    so we use F.nll_loss (negative log-likelihood) — equivalent to cross-entropy
    but without the second log_softmax that F.cross_entropy would apply.

    The value head is frozen during BC pretraining: it has no supervision signal
    (we have expert actions, not value targets) and training it with zero-initialized
    weights would inject gradient noise that corrupts the backbone.

Model-to-checkpoint mapping:
    dqn         → checkpoints/bc_pretrained.pt            (unchanged, existing tooling)
    baseline    → checkpoints/bc_pretrained_baseline.pt
    resnet      → checkpoints/bc_pretrained_resnet.pt
    bfs         → checkpoints/bc_pretrained_bfs.pt
    bfs_resnet  → checkpoints/bc_pretrained_bfs_resnet.pt

Dataset-to-model pairing:
    4-channel models (dqn, baseline, resnet):  --data data/bc_data.npz
    6-channel models (bfs, bfs_resnet):        --data data/bc_data_bfs.npz

Usage:
    # DQN (unchanged)
    python scripts/pretrain_bc.py

    # bfs_resnet (6-channel)
    python scripts/pretrain_bc.py --model bfs_resnet --data data/bc_data_bfs.npz

    # baseline PPO (4-channel)
    python scripts/pretrain_bc.py --model baseline

    python scripts/pretrain_bc.py --model bfs_resnet --epochs 30   # more training
"""

import argparse
import os
import random

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

from config import BC_BATCH_SIZE, BC_EPOCHS, BC_LR, SEED

# PPO model class names — imported lazily inside main() to avoid circular imports
# and to keep the module importable even when some model files aren't present.
_PPO_MODELS = ("baseline", "resnet", "bfs", "bfs_resnet")


def load_dataset(path: str, device: torch.device) -> TensorDataset:
    """Load bc_data.npz (or bc_data_bfs.npz) and wrap as a TensorDataset."""
    data = np.load(path)
    spatial     = torch.tensor(data["spatial"]).to(device)      # (N, C, 9, 9)
    scalars     = torch.tensor(data["scalars"]).to(device)      # (N, 2)
    legal_masks = torch.tensor(data["legal_masks"]).to(device)  # (N, 137) bool
    actions     = torch.tensor(data["actions"]).to(device)      # (N,) int64
    print(
        f"Loaded {actions.shape[0]:,} samples from {path}  "
        f"(spatial: {tuple(spatial.shape)})"
    )
    return TensorDataset(spatial, scalars, legal_masks, actions)


def train(
    model,
    dataset:     TensorDataset,
    device:      torch.device,
    epochs:      int,
    batch_size:  int,
    lr:          float,
    model_name:  str,
    use_wandb:   bool,
) -> None:
    """
    Run the supervised BC training loop.

    For DQN: forward returns logits directly; use F.cross_entropy.
    For PPO: forward returns (Categorical, value); use F.nll_loss on dist.logits
             (which are already log-softmax'd masked logits).

    The value_head is frozen before this function is called (for PPO models),
    so only backbone + actor_head parameters are in the optimizer.
    """
    # Freeze value_head for PPO models — no supervision signal for value targets.
    # Must happen before constructing the optimizer so frozen params are excluded.
    is_ppo = model_name in _PPO_MODELS
    if is_ppo:
        for name, param in model.named_parameters():
            if name.startswith("value_head"):
                param.requires_grad = False

    trainable_params = [p for p in model.parameters() if p.requires_grad]
    optimizer  = torch.optim.Adam(trainable_params, lr=lr)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    if use_wandb:
        import wandb
        wandb_project = "quoridor-ppo" if is_ppo else "quoridor-dqn"
        wandb.init(
            project=wandb_project,
            job_type="bc_pretrain",
            config={
                "model":      model_name,
                "epochs":     epochs,
                "batch_size": batch_size,
                "lr":         lr,
                "n_samples":  len(dataset),
                "device":     str(device),
            },
        )

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss  = 0.0
        total_acc   = 0
        total_seen  = 0

        for spatial, scalars, legal_masks, actions in dataloader:
            if is_ppo:
                # PPO forward returns (Categorical, value_tensor).
                # dist.logits = log_softmax(masked_raw_logits) — already normalized.
                # F.nll_loss(log_probs, targets) = -log_probs[targets] = cross-entropy.
                # Do NOT use F.cross_entropy here — it would apply log_softmax twice.
                dist, _ = model(spatial, scalars, legal_masks)   # (Categorical, (B,1))
                log_probs = dist.logits                          # (B, 137)
                loss  = F.nll_loss(log_probs, actions)
                preds = log_probs.argmax(dim=1)                  # (B,)
            else:
                # DQN forward returns masked Q-values as logits.
                # Illegal actions are set to -1e9 so they never win argmax / softmax.
                logits = model(spatial, scalars, legal_masks)    # (B, 137)
                loss   = F.cross_entropy(logits, actions)
                preds  = logits.argmax(dim=1)                    # (B,)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss  += loss.item() * spatial.shape[0]
            total_acc   += (preds == actions).sum().item()
            total_seen  += spatial.shape[0]

        epoch_loss = total_loss / total_seen
        epoch_acc  = total_acc  / total_seen
        print(
            f"Epoch {epoch:>3}/{epochs}  |  "
            f"loss={epoch_loss:.4f}  |  "
            f"action_accuracy={epoch_acc:.2%}"
        )

        if use_wandb:
            import wandb
            wandb.log({
                "bc/loss":            epoch_loss,
                "bc/action_accuracy": epoch_acc,
            }, step=epoch)

    if use_wandb:
        import wandb
        wandb.finish()


def main(args) -> None:
    # --- Device ---
    if torch.backends.mps.is_available():
        device = torch.device("mps")
    elif torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")
    print(f"Device: {device}")

    # --- Reproducibility ---
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    random.seed(SEED)

    # --- Data ---
    dataset = load_dataset(args.data, device)

    # --- Model ---
    if args.model == "dqn":
        from agents.dqn_model import DQNModel
        model = DQNModel().to(device)
    elif args.model == "baseline":
        from agents.ppo_model import PPOModel
        model = PPOModel().to(device)
    elif args.model == "resnet":
        from agents.ppo_model_resnet import PPOModelResNet
        model = PPOModelResNet().to(device)
    elif args.model == "bfs":
        from agents.ppo_model_bfs import PPOModelBFS
        model = PPOModelBFS().to(device)
    elif args.model == "bfs_resnet":
        from agents.ppo_model_bfs_resnet import PPOModelBFSResNet
        model = PPOModelBFSResNet().to(device)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"Model: {args.model}  |  parameters: {total_params:,}")

    # --- Train ---
    print(
        f"\nStarting BC pretraining: {args.epochs} epochs, "
        f"LR={args.lr}, batch={args.batch_size}"
    )
    train(
        model      = model,
        dataset    = dataset,
        device     = device,
        epochs     = args.epochs,
        batch_size = args.batch_size,
        lr         = args.lr,
        model_name = args.model,
        use_wandb  = not args.no_wandb,
    )

    # --- Save ---
    os.makedirs("checkpoints", exist_ok=True)
    if args.model == "dqn":
        out_path = "checkpoints/bc_pretrained.pt"
    else:
        out_path = f"checkpoints/bc_pretrained_{args.model}.pt"
    torch.save(model.state_dict(), out_path)
    print(f"\nBC pretrained checkpoint saved: {out_path}")

    if args.model == "dqn":
        print(
            "Next step: python scripts/train_dqn.py "
            "--opponent heuristic --checkpoint checkpoints/bc_pretrained.pt"
        )
    else:
        print(
            f"Next step: python -m scripts.train_ppo "
            f"--model {args.model} --checkpoint {out_path}"
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Behavioral cloning pretraining for DQN and PPO models."
    )
    parser.add_argument(
        "--model",
        type=str,
        default="dqn",
        choices=["dqn", "baseline", "resnet", "bfs", "bfs_resnet"],
        help=(
            "Model architecture to pretrain. "
            "'dqn' preserves existing DQN workflow (default). "
            "'bfs' and 'bfs_resnet' require --data data/bc_data_bfs.npz."
        ),
    )
    parser.add_argument(
        "--data",
        type=str,
        default="data/bc_data.npz",
        help=(
            "Path to the bc_data.npz file produced by generate_bc_data.py. "
            "Use data/bc_data_bfs.npz for bfs/bfs_resnet models."
        ),
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=BC_EPOCHS,
        help=f"Number of training epochs (default: {BC_EPOCHS}).",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=BC_LR,
        help=f"Learning rate (default: {BC_LR}).",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=BC_BATCH_SIZE,
        dest="batch_size",
        help=f"Mini-batch size (default: {BC_BATCH_SIZE}).",
    )
    parser.add_argument(
        "--no-wandb",
        action="store_true",
        help="Disable Weights & Biases logging.",
    )
    args = parser.parse_args()
    main(args)
